name: medi_mind
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  dots_indicator: ^3.0.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  gap: ^3.0.1
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  get_it: ^7.7.0
  injectable: ^2.4.1
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  hive_flutter: ^1.1.0
  rxdart: ^0.27.7
  talker_flutter: ^4.2.0
  talker_bloc_logger: ^4.2.0
  adaptive_dialog: ^2.1.0
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  go_router_builder: ^2.5.1
  injectable_generator: ^2.6.1
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lint: ^2.3.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
