// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaarNVQSTt6XWMV6EiOFM4WnU7iURHqoo',
    appId: '1:300015691592:web:28d2600c5189870603757d',
    messagingSenderId: '300015691592',
    projectId: 'medi-mind-da69b',
    authDomain: 'medi-mind-da69b.firebaseapp.com',
    storageBucket: 'medi-mind-da69b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbqEHC9hkWg1Ov3WnHQlKO4tA9BJcF30',
    appId: '1:300015691592:android:d0b2d2ef6cefb3a003757d',
    messagingSenderId: '300015691592',
    projectId: 'medi-mind-da69b',
    storageBucket: 'medi-mind-da69b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3fALHC7VrhirIg8_RlsumdZEvnt3J23Y',
    appId: '1:300015691592:ios:3339cb0331c369a203757d',
    messagingSenderId: '300015691592',
    projectId: 'medi-mind-da69b',
    storageBucket: 'medi-mind-da69b.appspot.com',
    iosBundleId: 'com.use4k.medi_mind',
  );
}
